# Generated by Django 4.2.1 on 2023-05-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('device_id', models.CharField(help_text="Enter Device's Name", max_length=20, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(help_text="Enter Device's Location", max_length=50)),
                ('data', models.FloatField(help_text='Sensor Reading')),
            ],
            options={
                'ordering': ['device_id', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('response_id', models.CharField(help_text="Enter Response's ID", max_length=20, primary_key=True, serialize=False)),
                ('expert_id', models.CharField(help_text="Enter Expert's ID", max_length=20)),
                ('destination_device', models.CharField(help_text="Enter Destination Device's Name", max_length=20)),
                ('is_unsafe', models.BooleanField(default=False, help_text='True if the water is contaminated')),
                ('valve_shutoff', models.BooleanField(default=False, help_text='True if the water is contaminated')),
            ],
            options={
                'ordering': ['response_id', 'destination_device', 'is_unsafe'],
            },
        ),
    ]
