# Generated by Django 3.2.16 on 2023-06-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_remove_sensor_tunnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdata',
            name='destination_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor'),
        ),
    ]
